/* 术语表 */
window.ISPM = window.ISPM || {};

ISPM.terms = [
  { id: 'wbs', name: 'WBS', en: 'Work Breakdown Structure', def: '将项目可交付成果和项目工作分解为较小的、更易管理的组件的过程。WBS 的最底层是工作包。', analogy: '像搬家时把"搬家"拆成找公司、打包、搬运等小任务', module: 'pm-scope' },
  { id: 'work-package', name: '工作包', en: 'Work Package', def: 'WBS 最底层的可交付成果，可以被可靠地估算成本和持续时间，通常在 8-80 小时范围内。', analogy: '像乐高积木中最小的可拼接单元', module: 'pm-scope' },
  { id: 'scope-baseline', name: '范围基准', en: 'Scope Baseline', def: '经批准的范围说明书、WBS 和 WBS 词典，用于比较实际结果与计划的偏差。', analogy: '像建筑的设计蓝图，一切施工都以此为准', module: 'pm-scope' },
  { id: 'scope-creep', name: '范围蔓延', en: 'Scope Creep', def: '未经控制的产品或项目范围扩大，未经过正式变更控制程序。', analogy: '像装修时不断加需求——再加个飘窗、再改个吊顶', module: 'pm-scope' },
  { id: 'critical-path', name: '关键路径', en: 'Critical Path', def: '项目网络图中最长的路径，决定了项目的最短完成时间。关键路径上的活动总浮动时间为零。', analogy: '像做饭时最耗时的那道菜决定了上菜时间', module: 'pm-schedule' },
  { id: 'float', name: '浮动时间', en: 'Float/Slack', def: '在不延迟项目完成日期的前提下，某活动可以延迟的时间量。关键路径上浮动时间为零。', analogy: '像赶火车时，提前到的富余时间', module: 'pm-schedule' },
  { id: 'evm', name: '挣值管理', en: 'Earned Value Management', def: '整合范围、进度和成本的绩效测量方法。通过 PV、EV、AC 三个基本参数衡量项目健康状况。', analogy: '像体检报告，用几个指标全面反映项目的"健康状况"', module: 'pm-cost' },
  { id: 'pv', name: 'PV 计划价值', en: 'Planned Value', def: '截至某时间点，计划完成工作的预算成本。代表"应该完成多少"的金额。', analogy: '像每月储蓄计划中"到这个月应该存了多少"', module: 'pm-cost' },
  { id: 'ev', name: 'EV 挣值', en: 'Earned Value', def: '截至某时间点，实际完成工作的预算成本。代表"实际完成了多少"的价值。', analogy: '像实际已经存入银行的金额', module: 'pm-cost' },
  { id: 'ac', name: 'AC 实际成本', en: 'Actual Cost', def: '截至某时间点，完成工作实际花费的总成本。代表"花了多少钱"。', analogy: '像信用卡账单上的实际支出', module: 'pm-cost' },
  { id: 'spi', name: 'SPI 进度绩效指数', en: 'Schedule Performance Index', def: 'EV/PV，衡量进度效率。SPI>1 表示超前，SPI<1 表示落后。', analogy: '像速度表：大于1是超速（提前），小于1是慢了', module: 'pm-cost' },
  { id: 'cpi', name: 'CPI 成本绩效指数', en: 'Cost Performance Index', def: 'EV/AC，衡量成本效率。CPI>1 表示节约，CPI<1 表示超支。', analogy: '像购物的性价比：大于1是赚了，小于1是亏了', module: 'pm-cost' },
  { id: 'risk-register', name: '风险登记册', en: 'Risk Register', def: '记录已识别风险的详细信息，包括描述、类别、原因、概率、影响、应对措施等。', analogy: '像医院的病历本，记录所有"已知疾病"和治疗方案', module: 'pm-risk' },
  { id: 'risk-response', name: '风险应对策略', en: 'Risk Response Strategy', def: '针对威胁：规避、转移、减轻、接受；针对机会：开拓、分享、提高、接受。', analogy: '像面对暴风雨：改航线（规避）、买保险（转移）、加固船体（减轻）、硬扛（接受）', module: 'pm-risk' },
  { id: 'change-control', name: '变更控制', en: 'Change Control', def: '识别、记录、批准或拒绝对项目文件、可交付成果或基准的修改的过程。', analogy: '像公司的审批流程——改方案不能口头说了算，要走流程', module: 'pm-integ' },
  { id: 'ccb', name: 'CCB 变更控制委员会', en: 'Change Control Board', def: '正式组成的团体，负责审查、评估、批准、推迟或否决项目变更。', analogy: '像公司的"项目变更审批会"，集体决策不是一个人说了算', module: 'pm-integ' },
  { id: 'configuration-management', name: '配置管理', en: 'Configuration Management', def: '识别和记录产品及其组件的功能特征和物理特征，控制变更，记录和报告变更状态。', analogy: '像给每个版本打标签、存档，随时能回溯到任何版本', module: 'pm-integ' },
  { id: 'project-charter', name: '项目章程', en: 'Project Charter', def: '由项目发起人签发的、正式批准项目存在并授权项目经理使用资源的文件。', analogy: '像皇帝的圣旨——给项目经理"尚方宝剑"', module: 'pm-integ' },
  { id: 'stakeholder', name: '干系人', en: 'Stakeholder', def: '能影响项目决策、活动或结果的个人、群体或组织，或受项目影响的对象。', analogy: '像一部电影的所有利益相关方：投资人、导演、演员、观众', module: 'pm-hr' },
  { id: 'raci', name: 'RACI矩阵', en: 'RACI Matrix', def: '责任分配矩阵。R=执行、A=负责、C=咨询、I=知会，明确每项工作的角色分工。', analogy: '像饭店分工表：谁炒菜(R)、谁拍板(A)、谁提意见(C)、谁只需知道(I)', module: 'pm-hr' },
  { id: 'cmmi', name: 'CMMI', en: 'Capability Maturity Model Integration', def: '能力成熟度模型集成，分5个等级：初始级、已管理级、已定义级、量化管理级、优化级。', analogy: '像武林等级：从散打新手到宗师，每级有明确的能力要求', module: 'se' },
  { id: 'agile', name: '敏捷方法', en: 'Agile', def: '以人为核心、迭代、循序渐进的开发方法。强调快速交付、响应变化、客户协作。', analogy: '像写连载小说——边写边根据读者反馈调整剧情', module: 'se' },
  { id: 'pdca', name: 'PDCA循环', en: 'Plan-Do-Check-Act', def: '质量持续改进的基本方法。计划→执行→检查→行动，循环往复、螺旋上升。', analogy: '像健身：制定计划→执行训练→称体重看效果→调整方案', module: 'pm-quality' },
  { id: 'pareto', name: '帕累托图', en: 'Pareto Chart', def: '按频率排序的柱状图+累计百分比曲线，用于识别最重要的少数原因（80/20法则）。', analogy: '像找出导致80%投诉的那20%问题', module: 'pm-quality' },
  { id: 'fptp', name: '总价合同', en: 'Fixed-Price Contract', def: '为已明确的产品或服务设定固定总价。卖方承担成本超支风险。', analogy: '像装修包干价——多花少花都是装修公司的事', module: 'pm-proc' },
  { id: 'cpff', name: '成本补偿合同', en: 'Cost-Reimbursable Contract', def: '买方向卖方支付实际成本加上费用（利润）。买方承担成本超支风险。', analogy: '像按实际工时付费的律师——花多少算多少再加服务费', module: 'pm-proc' },
  { id: 'opm3', name: 'OPM3', en: 'Organizational Project Management Maturity Model', def: '组织级项目管理成熟度模型，评估组织在项目、项目集、组合管理方面的能力。', analogy: '像企业管理能力的"段位考试"', module: 'program' },
  { id: 'project-portfolio', name: '项目组合', en: 'Project Portfolio', def: '为实现战略目标而组合在一起管理的项目、项目集和子组合的集合。', analogy: '像投资组合——为了整体收益最大化而搭配的一组投资', module: 'program' },
  { id: 'probability-impact', name: '概率影响矩阵', en: 'Probability and Impact Matrix', def: '定性风险分析的核心工具，将风险的发生概率与影响程度交叉，计算风险值（概率×影响）并据此分级排序。', analogy: '像给风险打分排座次——既看它多可能发生，又看发生了有多严重', module: 'pm-risk' },
  { id: 'emv', name: '期望货币价值', en: 'Expected Monetary Value', def: '定量风险分析指标，EMV = 概率 × 影响金额。威胁取负、机会取正，常用于决策树分析。', analogy: '像赌局的数学期望——把"可能性"和"输赢金额"相乘算出平均预期', module: 'pm-risk' },
  { id: 'eac', name: '完工估算', en: 'Estimate At Completion', def: '预计项目完工时的总成本。偏差持续时 EAC = BAC/CPI；偏差为一次性时 EAC = AC + (BAC−EV)。', analogy: '像根据已花的钱和当前效率，预测整趟旅行最终要花多少', module: 'pm-cost' },
  { id: 'tucker', name: '塔克曼阶梯', en: 'Tuckman Ladder', def: '团队发展五阶段模型：形成期、震荡期、规范期、成熟期、解散期。震荡期冲突最多，成熟期绩效最高。', analogy: '像一支新乐队从磨合、争吵到默契演出的成长过程', module: 'pm-hr' },
  { id: 'critical-path-method', name: '关键路径法', en: 'Critical Path Method', def: '通过前向、后向计算确定网络图中最长路径（关键路径）的方法，决定项目最短工期。关键路径上总浮动为零。', analogy: '像找出一串工序里最耗时的主线，它决定了整体最快多久完工', module: 'pm-schedule' },
  { id: 'cloud-computing', name: '云计算', en: 'Cloud Computing', def: '按需提供可配置计算资源的服务模式，分 IaaS（基础设施）、PaaS（平台）、SaaS（软件）三层。', analogy: '像用水用电——按需取用、按量付费，不用自己建水厂电厂', module: 'overview' },
  { id: 'agile-scrum', name: 'Scrum', en: 'Scrum', def: '最常用的敏捷框架。三角色（PO、Scrum Master、开发团队）、五事件（冲刺及四会）、三工件（产品/冲刺待办、增量）。', analogy: '像橄榄球争球——小团队短周期快速冲刺、紧密协作', module: 'se' },
  { id: 'five-process-groups', name: '五大过程组', en: 'Five Process Groups', def: '启动、规划、执行、监控、收尾。每个项目都要经历这五个过程组。', analogy: '像做菜：决定做什么(启动)、买菜备料(规划)、炒菜(执行)、尝味道(监控)、装盘(收尾)', module: 'pm-framework' },
  { id: 'ten-knowledge-areas', name: '十大知识领域', en: 'Ten Knowledge Areas', def: '整合、范围、进度、成本、质量、资源、沟通、风险、采购、干系人管理。', analogy: '像管理一个家：要管钱(成本)、管时间(进度)、管质量(质量)、管人(资源)...', module: 'pm-framework' }
];
