/* generated by tools/build.js */
window.CDC=window.CDC||{};
CDC.META=CDC.META||{};CDC.META.ndiseases=3;
CDC.modules=[
 {
  "id": "hypertension",
  "name": "高血压",
  "icon": "🫀",
  "soft": "var(--alert-soft)",
  "desc": "诊断标准、家庭测量、限盐技巧、降压药常识、危险信号识别。",
  "lessons": [
   {
    "id": "hypertension-01",
    "title": "血压到底是什么？先认识这套\"水压系统\""
   },
   {
    "id": "hypertension-02",
    "title": "为什么会得高血压？三个因素排排坐"
   },
   {
    "id": "hypertension-03",
    "title": "心脑肾眼：高血压的长期账单"
   },
   {
    "id": "hypertension-04",
    "title": "140/90 不是随便定的：诊断标准怎么读"
   },
   {
    "id": "hypertension-05",
    "title": "在家测血压的 5 个正确姿势"
   },
   {
    "id": "hypertension-06",
    "title": "限盐不是不吃盐：藏在厨房里的钠"
   },
   {
    "id": "hypertension-07",
    "title": "减肥就是降压药：体重和血压的账"
   },
   {
    "id": "hypertension-08",
    "title": "动起来：快走就是最好的处方"
   },
   {
    "id": "hypertension-09",
    "title": "酒：一杯都是负担"
   },
   {
    "id": "hypertension-10",
    "title": "戒烟：为血管止损"
   },
   {
    "id": "hypertension-11",
    "title": "压力和睡眠：被忽视的升压阀"
   },
   {
    "id": "hypertension-12",
    "title": "季节与血压：换季的账怎么算"
   },
   {
    "id": "hypertension-13",
    "title": "降压药常识（上）：五大类各管一段"
   },
   {
    "id": "hypertension-14",
    "title": "降压药常识（下）：这些坑别踩"
   },
   {
    "id": "hypertension-15",
    "title": "危险信号：这些症状别等"
   },
   {
    "id": "hypertension-16",
    "title": "并发症治疗地图（上）：脑卒中来了怎么办"
   },
   {
    "id": "hypertension-17",
    "title": "并发症治疗地图（下）：心衰、肾衰与眼底"
   }
  ]
 },
 {
  "id": "diabetes",
  "name": "2 型糖尿病",
  "icon": "🩸",
  "soft": "var(--warn-soft)",
  "desc": "血糖曲线、糖化血红蛋白、主食怎么吃、低血糖自救、并发症筛查。",
  "lessons": [
   {
    "id": "diabetes-01",
    "title": "血糖是怎么回事：从一块馒头说起"
   },
   {
    "id": "diabetes-02",
    "title": "1 型还是 2 型：不是年龄说了算"
   },
   {
    "id": "diabetes-03",
    "title": "诊断线：6.1、7.0、6.5 各是什么意思"
   },
   {
    "id": "diabetes-04",
    "title": "餐后血糖为什么比空腹更狡猾"
   },
   {
    "id": "diabetes-05",
    "title": "主食怎么吃：不是不吃，是会吃"
   },
   {
    "id": "diabetes-06",
    "title": "糖化血红蛋白：你的学期成绩单"
   },
   {
    "id": "diabetes-07",
    "title": "低血糖：比高血糖更急的敌人"
   },
   {
    "id": "diabetes-08",
    "title": "并发症：高血糖是怎么伤人的"
   },
   {
    "id": "diabetes-09",
    "title": "足部护理：每天 60 秒的必修课"
   },
   {
    "id": "diabetes-10",
    "title": "急性并发症：酮症酸中毒与高渗高血糖"
   },
   {
    "id": "diabetes-11",
    "title": "慢性并发症：糖尿病足——滑坡的每一步都能踩刹车"
   },
   {
    "id": "diabetes-12",
    "title": "慢性并发症：眼睛与肾脏——两个沉默的受害者"
   },
   {
    "id": "diabetes-13",
    "title": "每年该查什么：并发症筛查清单"
   },
   {
    "id": "diabetes-14",
    "title": "吃：餐盘法则实战版"
   },
   {
    "id": "diabetes-15",
    "title": "动：控糖的运动账"
   },
   {
    "id": "diabetes-16",
    "title": "减轻 5%：身体给你的一次机会"
   },
   {
    "id": "diabetes-17",
    "title": "糖友用药地图：从二甲双胍到胰岛素"
   },
   {
    "id": "diabetes-18",
    "title": "监测节奏：什么时候测、测多少"
   }
  ]
 },
 {
  "id": "lipids",
  "name": "血脂异常",
  "icon": "🧪",
  "soft": "var(--purple-soft)",
  "desc": "看懂血脂报告单、\"好胆固醇/坏胆固醇\"、他汀类药物、饮食调整。",
  "lessons": [
   {
    "id": "lipids-01",
    "title": "看懂血脂报告单：四项各管什么"
   },
   {
    "id": "lipids-02",
    "title": "血管怎么被堵上的：斑块的一生"
   },
   {
    "id": "lipids-03",
    "title": "好胆固醇 HDL：别指望它太高，别让它太低"
   },
   {
    "id": "lipids-04",
    "title": "甘油三酯：吃出来的血脂"
   },
   {
    "id": "lipids-05",
    "title": "他汀：证据最硬的降脂药"
   },
   {
    "id": "lipids-06",
    "title": "他汀之外的降脂选择"
   },
   {
    "id": "lipids-07",
    "title": "吃：降脂饮食的红绿灯"
   },
   {
    "id": "lipids-08",
    "title": "体检报告背后：风险分层决定目标"
   },
   {
    "id": "lipids-09",
    "title": "家族性高胆固醇：少数人的特殊赛道"
   },
   {
    "id": "lipids-10",
    "title": "脂蛋白(a)：一生测一次的遗传指标"
   },
   {
    "id": "lipids-11",
    "title": "并发症治疗地图（上）：心梗——斑块破裂的那一夜"
   },
   {
    "id": "lipids-12",
    "title": "并发症治疗地图（下）：小中风、颈动脉与腿上的血管事件"
   }
  ]
 },
 {
  "id": "diet-move",
  "name": "饮食与运动",
  "icon": "🥗",
  "soft": "var(--teal-soft)",
  "desc": "DASH 饮食、餐盘法则、快走方案、运动强度自测，吃得明白动得安全。",
  "lessons": [
   {
    "id": "diet-move-01",
    "title": "DASH 饮食：为降压而生的吃法"
   },
   {
    "id": "diet-move-02",
    "title": "升糖指数：同是主食，命运不同"
   },
   {
    "id": "diet-move-03",
    "title": "蛋白质：每一餐的\"压舱石\""
   },
   {
    "id": "diet-move-04",
    "title": "进餐顺序与进食速度：免费的控糖药"
   },
   {
    "id": "diet-move-05",
    "title": "运动的四个处方要素：FITT"
   },
   {
    "id": "diet-move-06",
    "title": "力量训练：中年以后最划算的投资"
   },
   {
    "id": "diet-move-07",
    "title": "走路：最被低估的运动"
   },
   {
    "id": "diet-move-08",
    "title": "吃外食与过节：不崩盘的实战术"
   },
   {
    "id": "diet-move-09",
    "title": "体重平台期：身体在重新谈判"
   },
   {
    "id": "diet-move-10",
    "title": "喝水、咖啡与茶：饮料里的名堂"
   },
   {
    "id": "diet-move-11",
    "title": "运动安全：什么时候该停"
   }
  ]
 },
 {
  "id": "medication",
  "name": "用药与监测",
  "icon": "💊",
  "soft": "var(--ok-soft)",
  "desc": "漏服怎么办、能不能自行停药、家庭监测记录、何时该复诊。",
  "lessons": [
   {
    "id": "medication-01",
    "title": "慢病用药的总原则：规律压倒一切"
   },
   {
    "id": "medication-02",
    "title": "血压正常了，可以停药吗"
   },
   {
    "id": "medication-03",
    "title": "漏服与错服：补救手册"
   },
   {
    "id": "medication-04",
    "title": "看懂说明书：重点只看这几栏"
   },
   {
    "id": "medication-05",
    "title": "保健品与处方药：边界在哪"
   },
   {
    "id": "medication-06",
    "title": "家庭血压监测：数据这样记才值钱"
   },
   {
    "id": "medication-07",
    "title": "血糖仪使用：数字准不准，手法占一半"
   },
   {
    "id": "medication-08",
    "title": "体检报告读法：慢病人群的专属视角"
   },
   {
    "id": "medication-09",
    "title": "复诊节奏：多久见医生一次"
   },
   {
    "id": "medication-10",
    "title": "药物存放大有讲究"
   },
   {
    "id": "medication-11",
    "title": "用一个药盒管理五种药：系统化流程"
   }
  ]
 },
 {
  "id": "visit",
  "name": "就医与随访",
  "icon": "🏥",
  "soft": "var(--blue-soft)",
  "desc": "挂号科室选择、体检报告解读、慢病随访档案、医保与慢病门诊。",
  "lessons": [
   {
    "id": "visit-01",
    "title": "慢病该挂哪个科：一张导诊图"
   },
   {
    "id": "visit-02",
    "title": "首次就诊：三样东西带齐"
   },
   {
    "id": "visit-03",
    "title": "听懂医生的话：医嘱里的\"行话\""
   },
   {
    "id": "visit-04",
    "title": "慢病随访档案：你的健康账本"
   },
   {
    "id": "visit-05",
    "title": "医保与慢病门诊：该申请的待遇"
   },
   {
    "id": "visit-06",
    "title": "体检怎么选：慢病人群的年度清单"
   },
   {
    "id": "visit-07",
    "title": "住院与手术：慢病患者注意事项"
   },
   {
    "id": "visit-08",
    "title": "急诊与急救：哪些情况直接去医院"
   },
   {
    "id": "visit-09",
    "title": "看懂出院小结：交接棒别掉地上"
   },
   {
    "id": "visit-10",
    "title": "异地就医与网上问诊：新时代技能"
   },
   {
    "id": "visit-11",
    "title": "全家总动员：家属在慢病管理中的角色"
   },
   {
    "id": "visit-12",
    "title": "慢病谣言粉碎机：这些\"偏方\"别再传了"
   },
   {
    "id": "visit-13",
    "title": "慢病人群的疫苗清单：每年该打什么"
   },
   {
    "id": "visit-14",
    "title": "心理账本：慢病是马拉松，心态是配速"
   }
  ]
 }
];
CDC.flatLessons=["hypertension-01","hypertension-02","hypertension-03","hypertension-04","hypertension-05","hypertension-06","hypertension-07","hypertension-08","hypertension-09","hypertension-10","hypertension-11","hypertension-12","hypertension-13","hypertension-14","hypertension-15","hypertension-16","hypertension-17","diabetes-01","diabetes-02","diabetes-03","diabetes-04","diabetes-05","diabetes-06","diabetes-07","diabetes-08","diabetes-09","diabetes-10","diabetes-11","diabetes-12","diabetes-13","diabetes-14","diabetes-15","diabetes-16","diabetes-17","diabetes-18","lipids-01","lipids-02","lipids-03","lipids-04","lipids-05","lipids-06","lipids-07","lipids-08","lipids-09","lipids-10","lipids-11","lipids-12","diet-move-01","diet-move-02","diet-move-03","diet-move-04","diet-move-05","diet-move-06","diet-move-07","diet-move-08","diet-move-09","diet-move-10","diet-move-11","medication-01","medication-02","medication-03","medication-04","medication-05","medication-06","medication-07","medication-08","medication-09","medication-10","medication-11","visit-01","visit-02","visit-03","visit-04","visit-05","visit-06","visit-07","visit-08","visit-09","visit-10","visit-11","visit-12","visit-13","visit-14"];
