/* 世界历史学习站 · 模块元数据 + 课时路径 */
window.WHS = window.WHS || {};
(function(WHS) {
WHS.modules = [
  {
    "id": "origins",
    "title": "文明曙光",
    "tag": "Prehistory",
    "era": "史前·上古",
    "color": "--bronze",
    "ghost": "壹",
    "shortTitle": "文明曙光",
    "yearStart": "~前3500",
    "yearEnd": "前1200",
    "capital": "两河/尼罗河/印度河/黄河",
    "founder": "苏美尔·埃及·哈拉帕·商",
    "lastRuler": "城市与文字诞生",
    "generations": "数千年",
    "oneliner": "农业革命到四大古文明的起点",
    "desc": "人类走出非洲、农业革命、第一批城市与文字、青铜时代——四大古文明如何在大河边升起。",
    "lessons": 8
  },
  {
    "id": "near-east",
    "title": "两河与埃及",
    "tag": "Ancient",
    "era": "古代·近东",
    "color": "--gold",
    "ghost": "貳",
    "shortTitle": "两河埃及",
    "yearStart": "~前3000",
    "yearEnd": "前330",
    "capital": "巴比伦/孟菲斯/波斯波利斯",
    "founder": "苏美尔·埃及·波斯",
    "lastRuler": "波斯帝国一统近东",
    "generations": "两千余年",
    "oneliner": "人类最早的国家、法典与帝国",
    "desc": "苏美尔城邦、阿卡德与巴比伦、汉谟拉比法典、古埃及法老、希伯来一神教、亚述与波斯帝国。",
    "lessons": 9
  },
  {
    "id": "classical",
    "title": "古典希腊罗马",
    "tag": "Classical",
    "era": "古典·地中海",
    "color": "--crimson",
    "ghost": "叁",
    "shortTitle": "希腊罗马",
    "yearStart": "~前800",
    "yearEnd": "476",
    "capital": "雅典/罗马",
    "founder": "希腊城邦·罗马",
    "lastRuler": "西罗马灭亡",
    "generations": "一千余年",
    "oneliner": "西方政治哲学与帝国的源头",
    "desc": "希腊城邦与民主、希波战争、苏格拉底师徒、亚历山大帝国;罗马从共和到帝国,直至西罗马陷落。",
    "lessons": 14
  },
  {
    "id": "asia-classical",
    "title": "古代亚洲文明",
    "tag": "Asia",
    "era": "古典·亚洲",
    "color": "--olive",
    "ghost": "肆",
    "shortTitle": "古代亚洲",
    "yearStart": "~前2500",
    "yearEnd": "600",
    "capital": "印度河/华氏城",
    "founder": "哈拉帕·孔雀·笈多",
    "lastRuler": "佛教印度教定型",
    "generations": "三千年",
    "oneliner": "印度文明与丝路连接的东方世界",
    "desc": "印度河文明、吠陀与种姓、佛教与印度教、孔雀与笈多王朝、丝绸之路与草原游牧。",
    "lessons": 9
  },
  {
    "id": "middle-ages",
    "title": "中世纪欧洲",
    "tag": "Medieval",
    "era": "中古·欧洲",
    "color": "--slate",
    "ghost": "伍",
    "shortTitle": "中世纪",
    "yearStart": "476",
    "yearEnd": "1453",
    "capital": "君士坦丁堡/罗马",
    "founder": "法兰克·拜占庭",
    "lastRuler": "黑死病与百年战争",
    "generations": "近千年",
    "oneliner": "封建、教会与拜占庭的千年",
    "desc": "西罗马灭亡、拜占庭、查理曼与封建制、教会权威、维京人、十字军、黑死病与百年战争。",
    "lessons": 10
  },
  {
    "id": "islam",
    "title": "伊斯兰世界",
    "tag": "Islam",
    "era": "中古·伊斯兰",
    "color": "--jade",
    "ghost": "陸",
    "shortTitle": "伊斯兰",
    "yearStart": "610",
    "yearEnd": "1700",
    "capital": "麦地那/大马士革/巴格达",
    "founder": "阿拉伯·奥斯曼",
    "lastRuler": "三大火药帝国",
    "generations": "千余年",
    "oneliner": "横跨欧亚非的信仰与黄金时代",
    "desc": "伊斯兰兴起、穆罕默德、四大哈里发与倭马亚阿拔斯、黄金时代、安达卢斯、奥斯曼与莫卧儿。",
    "lessons": 9
  },
  {
    "id": "americas-africa",
    "title": "美洲与非洲",
    "tag": "Americas",
    "era": "古典·美非",
    "color": "--teal",
    "ghost": "柒",
    "shortTitle": "美洲非洲",
    "yearStart": "~前1200",
    "yearEnd": "1500",
    "capital": "特诺奇蒂特兰/库斯科/廷巴克图",
    "founder": "玛雅·阿兹特克·印加·马里",
    "lastRuler": "独立发展的文明",
    "generations": "数千年",
    "oneliner": "与旧大陆隔绝的独立文明",
    "desc": "中美洲奥尔梅克与玛雅、阿兹特克、安第斯印加;西非加纳马里桑海、东非斯瓦希里与大津巴布韦。",
    "lessons": 8
  },
  {
    "id": "renaissance",
    "title": "文艺复兴与大航海",
    "tag": "Renaissance",
    "era": "近代·开端",
    "color": "--plum",
    "ghost": "捌",
    "shortTitle": "文艺复兴",
    "yearStart": "1300",
    "yearEnd": "1600",
    "capital": "佛罗伦萨/里斯本/马德里",
    "founder": "意大利·葡萄牙·西班牙",
    "lastRuler": "全球连成一体",
    "generations": "三百年",
    "oneliner": "人文复兴与全球大连接",
    "desc": "意大利文艺复兴、人文主义、印刷术、宗教改革;葡西大航海、哥伦布、殖民帝国与哥伦布大交换。",
    "lessons": 11
  },
  {
    "id": "revolutions",
    "title": "革命时代",
    "tag": "Revolution",
    "era": "近代·革命",
    "color": "--rose",
    "ghost": "玖",
    "shortTitle": "革命时代",
    "yearStart": "1543",
    "yearEnd": "1815",
    "capital": "伦敦/巴黎/费城",
    "founder": "科学·启蒙·共和",
    "lastRuler": "拿破仑与维也纳体系",
    "generations": "两百余年",
    "oneliner": "科学、启蒙与三大革命",
    "desc": "科学革命、启蒙运动、绝对君主制;英国革命、美国独立、法国大革命与拿破仑、拉美独立与民族主义。",
    "lessons": 11
  },
  {
    "id": "industrial",
    "title": "工业革命与帝国主义",
    "tag": "Industrial",
    "era": "近代·工业",
    "color": "--mist",
    "ghost": "拾",
    "shortTitle": "工业帝国",
    "yearStart": "1760",
    "yearEnd": "1914",
    "capital": "曼彻斯特/柏林/东京",
    "founder": "英国·德国·日本",
    "lastRuler": "瓜分世界",
    "generations": "一个半世纪",
    "oneliner": "机器、民族国家与全球殖民",
    "desc": "两次工业革命、资本主义与社会主义、民族国家与德意统一、新帝国主义瓜分非洲、东亚的冲击与日本明治维新。",
    "lessons": 11
  },
  {
    "id": "world-wars",
    "title": "两次世界大战",
    "tag": "World Wars",
    "era": "现代·战争",
    "color": "--indigo",
    "ghost": "壹壹",
    "shortTitle": "世界大战",
    "yearStart": "1914",
    "yearEnd": "1945",
    "capital": "欧洲/全球",
    "founder": "同盟·协约·轴心",
    "lastRuler": "旧秩序崩塌",
    "generations": "三十余年",
    "oneliner": "人类最惨烈的两场全球战争",
    "desc": "一战与战壕、俄国革命、凡尔赛体系、大萧条、法西斯与纳粹、二战欧洲与太平洋战场、大屠杀与战后秩序。",
    "lessons": 12
  },
  {
    "id": "contemporary",
    "title": "冷战与当代世界",
    "tag": "Contemporary",
    "era": "当代·全球",
    "color": "--sky",
    "ghost": "壹貳",
    "shortTitle": "当代世界",
    "yearStart": "1945",
    "yearEnd": "至今",
    "capital": "华盛顿/莫斯科/全球",
    "founder": "美苏两极→多极",
    "lastRuler": "全球化与信息时代",
    "generations": "近八十年",
    "oneliner": "两极对峙到全球化的当下",
    "desc": "冷战起源与热点、去殖民化、第三世界、欧洲一体化、冷战终结、全球化、信息时代与 21 世纪格局。",
    "lessons": 10
  }
];
WHS.path = [
  "origins/01-human-origins",
  "origins/02-out-of-africa",
  "origins/03-agricultural-revolution",
  "origins/04-first-cities",
  "origins/05-writing",
  "origins/06-bronze-age",
  "origins/07-four-civilizations",
  "origins/08-river-valleys",
  "near-east/01-sumer",
  "near-east/02-akkad-babylon",
  "near-east/03-hammurabi",
  "near-east/04-egypt-old",
  "near-east/05-egypt-new",
  "near-east/06-hebrews",
  "near-east/07-phoenicians",
  "near-east/08-assyria",
  "near-east/09-persia",
  "classical/01-minoan-mycenae",
  "classical/02-greek-polis",
  "classical/03-sparta-athens",
  "classical/04-greco-persian-wars",
  "classical/05-athenian-democracy",
  "classical/06-peloponnesian-war",
  "classical/07-greek-philosophy",
  "classical/08-alexander",
  "classical/09-hellenistic",
  "classical/10-roman-republic",
  "classical/11-punic-wars",
  "classical/12-caesar-augustus",
  "classical/13-roman-empire",
  "classical/14-fall-of-rome",
  "asia-classical/01-indus",
  "asia-classical/02-vedic",
  "asia-classical/03-buddhism",
  "asia-classical/04-maurya",
  "asia-classical/05-gupta",
  "asia-classical/06-hinduism",
  "asia-classical/07-silk-road",
  "asia-classical/08-central-asia-nomads",
  "asia-classical/09-india-legacy",
  "middle-ages/01-byzantium",
  "middle-ages/02-franks-charlemagne",
  "middle-ages/03-feudalism",
  "middle-ages/04-church",
  "middle-ages/05-vikings",
  "middle-ages/06-crusades",
  "middle-ages/07-medieval-towns",
  "middle-ages/08-universities",
  "middle-ages/09-black-death",
  "middle-ages/10-hundred-years-war",
  "islam/01-arabia-before",
  "islam/02-muhammad",
  "islam/03-five-pillars",
  "islam/04-caliphates",
  "islam/05-umayyad-abbasid",
  "islam/06-golden-age",
  "islam/07-andalus",
  "islam/08-ottomans",
  "islam/09-safavid-mughal",
  "americas-africa/01-mesoamerica",
  "americas-africa/02-aztec",
  "americas-africa/03-inca",
  "americas-africa/04-north-america",
  "americas-africa/05-west-africa",
  "americas-africa/06-songhai",
  "americas-africa/07-east-africa",
  "americas-africa/08-great-zimbabwe",
  "renaissance/01-renaissance-italy",
  "renaissance/02-humanism",
  "renaissance/03-art-science",
  "renaissance/04-printing",
  "renaissance/05-reformation",
  "renaissance/06-counter-reformation",
  "renaissance/07-exploration",
  "renaissance/08-columbus",
  "renaissance/09-spanish-empire",
  "renaissance/10-columbian-exchange",
  "renaissance/11-slave-trade",
  "revolutions/01-scientific-revolution",
  "revolutions/02-enlightenment",
  "revolutions/03-absolutism",
  "revolutions/04-english-revolution",
  "revolutions/05-glorious-revolution",
  "revolutions/06-american-revolution",
  "revolutions/07-french-revolution",
  "revolutions/08-napoleon",
  "revolutions/09-latin-america",
  "revolutions/10-congress-vienna",
  "revolutions/11-nationalism",
  "industrial/01-industrial-revolution",
  "industrial/02-second-industrial",
  "industrial/03-capitalism-socialism",
  "industrial/04-german-italian-unification",
  "industrial/05-imperialism",
  "industrial/06-scramble-africa",
  "industrial/07-india-britain",
  "industrial/08-china-opium",
  "industrial/09-japan-meiji",
  "industrial/10-us-civil-war",
  "industrial/11-social-change",
  "world-wars/01-causes-ww1",
  "world-wars/02-ww1",
  "world-wars/03-russian-revolution",
  "world-wars/04-versailles",
  "world-wars/05-roaring-depression",
  "world-wars/06-fascism",
  "world-wars/07-nazi-germany",
  "world-wars/08-ww2-europe",
  "world-wars/09-ww2-pacific",
  "world-wars/10-holocaust",
  "world-wars/11-end-ww2",
  "world-wars/12-aftermath",
  "contemporary/01-cold-war-origins",
  "contemporary/02-cold-war-hotspots",
  "contemporary/03-decolonization",
  "contemporary/04-third-world",
  "contemporary/05-european-integration",
  "contemporary/06-end-cold-war",
  "contemporary/07-globalization",
  "contemporary/08-information-age",
  "contemporary/09-post-cold-war",
  "contemporary/10-21st-century"
];
WHS.totalLessons = WHS.path.length;
for (var i = 0; i < WHS.modules.length; i++) {
  var mId = WHS.modules[i].id;
  for (var j = 0; j < WHS.path.length; j++) {
    if (WHS.path[j].indexOf(mId + '/') === 0) { WHS.modules[i].firstLesson = WHS.path[j]; break; }
  }
}
})(window.WHS);
