/* 术语表 · 世界历史 */
window.WHS = window.WHS || {};
(function(WHS) {
WHS.terms = [
  {"id":"homo-sapiens","name":"智人","en":"Homo sapiens","module":"origins","def":"今天人类所属的物种，约 30 万年前出现于非洲，是唯一幸存的人属物种。","analogy":"我们自己。"},
  {"id":"paleolithic","name":"旧石器时代","en":"Paleolithic","module":"origins","def":"人类以打制石器、采集狩猎为生的漫长时期，占人类史绝大部分。","analogy":"人类的\"采集狩猎童年\"。"},
  {"id":"neanderthal","name":"尼安德特人","en":"Neanderthal","module":"origins","def":"曾与智人并存的古人类，约 4 万年前灭绝，今人仍带少量其基因。","analogy":"人类已灭绝的\"表亲\"。"},
  {"id":"agricultural-revolution","name":"农业革命","en":"Agricultural Revolution","module":"origins","def":"约 1 万年前人类开始种植与驯养，从游动采集转为定居农耕的大转折。","analogy":"人类历史的第一次\"大升级\"。"},
  {"id":"neolithic","name":"新石器时代","en":"Neolithic","module":"origins","def":"农业出现后，磨制石器、制陶、定居村落的时代。","analogy":"\"种地 + 定居\"的开端。"},
  {"id":"city-state","name":"城邦","en":"City-state","module":"origins","def":"以一座城市及其周边农田为单位的独立政治体，最早出现于苏美尔。","analogy":"一座城就是一个国家。"},
  {"id":"cuneiform","name":"楔形文字","en":"Cuneiform","module":"origins","def":"苏美尔人用芦苇笔在泥板上压出的楔形符号，最早的成熟文字之一。","analogy":"人类最早的\"账本文字\"。"},
  {"id":"hieroglyph","name":"圣书字","en":"Hieroglyph","module":"origins","def":"古埃及的象形文字，多用于宗教与王室铭文。","analogy":"埃及的\"图画文字\"。"},
  {"id":"bronze-age","name":"青铜时代","en":"Bronze Age","module":"origins","def":"人类掌握铜锡合金、广泛使用青铜工具武器的时代，催生远程贸易与早期帝国。","analogy":"金属时代的第一章。"},
  {"id":"megalith","name":"巨石建筑","en":"Megalith","module":"origins","def":"史前用巨大石块建造的遗迹，如巨石阵，用途多与天文或仪式有关。","analogy":"石器时代的\"大工程\"。"},
  {"id":"ziggurat","name":"吉库拉特","en":"Ziggurat","module":"near-east","def":"两河流域阶梯状的塔庙，是城邦的宗教与经济中心。","analogy":"苏美尔版\"金字塔神庙\"。"},
  {"id":"babylon","name":"巴比伦","en":"Babylon","module":"near-east","def":"两河流域古城与王国，汉谟拉比时兴盛，长期是两河文明的象征。","analogy":"古代两河的\"超级都市\"。"},
  {"id":"hammurabi-code","name":"汉谟拉比法典","en":"Code of Hammurabi","module":"near-east","def":"巴比伦国王颁布、保存最完整的早期成文法典，确立同态复仇原则。","analogy":"最早公开成文的\"国法\"。"},
  {"id":"pharaoh","name":"法老","en":"Pharaoh","module":"near-east","def":"古埃及国王的称号，被视为神在人间的化身，集王权与神权于一身。","analogy":"又是国王又是神。"},
  {"id":"pyramid","name":"金字塔","en":"Pyramid","module":"near-east","def":"古埃及法老的陵墓，体现来世信仰与强大的组织工程能力。","analogy":"法老的\"通天陵墓\"。"},
  {"id":"monotheism","name":"一神教","en":"Monotheism","module":"near-east","def":"只信仰唯一神的宗教传统，由希伯来人系统化，催生犹太、基督、伊斯兰教。","analogy":"\"只有一个神\"。"},
  {"id":"alphabet","name":"字母文字","en":"Alphabet","module":"near-east","def":"用少量表音符号记录语言的系统，源于腓尼基，是西方字母的祖先。","analogy":"用几十个符号拼出一切。"},
  {"id":"zoroastrianism","name":"琐罗亚斯德教","en":"Zoroastrianism","module":"near-east","def":"古波斯的宗教，强调善恶二元与最终审判，影响了后来的一神教。","analogy":"波斯的\"拜火教\"。"},
  {"id":"assyria","name":"亚述","en":"Assyria","module":"near-east","def":"近东第一个军事帝国，以铁器、战车和铁腕统治著称。","analogy":"古代的\"军事机器\"。"},
  {"id":"persian-empire","name":"波斯帝国","en":"Persian Empire","module":"near-east","def":"阿契美尼德王朝建立的古代最大帝国，以行省、御道与宽容治理著称。","analogy":"古代版\"多元大帝国\"。"},
  {"id":"polis","name":"城邦(希腊)","en":"Polis","module":"classical","def":"古希腊以公民共同体为核心的独立城市国家，如雅典、斯巴达。","analogy":"希腊式\"小国寡民\"。"},
  {"id":"democracy","name":"民主","en":"Democracy","module":"classical","def":"由公民共同决定公共事务的制度，源于古雅典的直接民主实践。","analogy":"\"人民统治\"。"},
  {"id":"hoplite","name":"重装步兵方阵","en":"Hoplite phalanx","module":"classical","def":"希腊公民组成的重装步兵密集队形，是城邦军事的核心。","analogy":"公民组成的\"人墙\"。"},
  {"id":"philosophy","name":"哲学","en":"Philosophy","module":"classical","def":"用理性追问世界与人生根本问题的思辨传统，希腊三贤奠基。","analogy":"\"爱智慧\"。"},
  {"id":"hellenism","name":"希腊化","en":"Hellenism","module":"classical","def":"亚历山大之后希腊文化向东扩散、与各文明融合的时代与现象。","analogy":"希腊文化的\"全球化 1.0\"。"},
  {"id":"senate","name":"元老院","en":"Senate","module":"classical","def":"罗马共和国由贵族组成、长期掌握实权的核心机构。","analogy":"罗马的\"权力中枢\"。"},
  {"id":"republic","name":"共和","en":"Republic","module":"classical","def":"以选举官员、分权制衡取代君主的政体，罗马共和国为典范。","analogy":"\"没有国王的国家\"。"},
  {"id":"punic-wars","name":"布匿战争","en":"Punic Wars","module":"classical","def":"罗马与迦太基为争夺地中海打的三场战争，罗马最终称霸。","analogy":"地中海的\"争霸赛\"。"},
  {"id":"pax-romana","name":"罗马和平","en":"Pax Romana","module":"classical","def":"奥古斯都开创、约两百年的帝国稳定繁荣时期。","analogy":"罗马治下的\"太平盛世\"。"},
  {"id":"christianity","name":"基督教","en":"Christianity","module":"classical","def":"源于犹太传统、以耶稣为救主的一神教，后成为罗马国教并传遍欧洲。","analogy":"从受迫害到国教。"},
  {"id":"caste-system","name":"种姓制度","en":"Caste system","module":"asia-classical","def":"印度世代相承、规定职业与通婚的社会等级制度，与轮回观念结合。","analogy":"生来注定的\"社会层级\"。"},
  {"id":"buddhism","name":"佛教","en":"Buddhism","module":"asia-classical","def":"释迦牟尼创立，主张众生平等、因缘业报、修行解脱的宗教。","analogy":"\"离苦得乐\"之道。"},
  {"id":"hinduism","name":"印度教","en":"Hinduism","module":"asia-classical","def":"吠陀以来层层累积的庞大信仰体系，无单一创始人，印度文明的底色。","analogy":"一个\"信仰大家族\"。"},
  {"id":"silk-road","name":"丝绸之路","en":"Silk Road","module":"asia-classical","def":"连接东亚、中亚、印度、波斯与地中海的贸易与文化交流网络。","analogy":"古代的\"洲际交流网\"。"},
  {"id":"vedas","name":"吠陀","en":"Vedas","module":"asia-classical","def":"雅利安人带来的印度最古老圣典，是印度教与种姓的源头。","analogy":"印度的\"上古经书\"。"},
  {"id":"byzantium","name":"拜占庭","en":"Byzantium","module":"middle-ages","def":"西罗马灭亡后延续千年的东罗马帝国，东正教与希腊罗马文明的守护者。","analogy":"\"活了一千年的东罗马\"。"},
  {"id":"feudalism","name":"封建制度","en":"Feudalism","module":"middle-ages","def":"中世纪西欧以土地换效忠、层层依附的政治与社会安排。","analogy":"\"以地换忠\"的金字塔。"},
  {"id":"papacy","name":"教皇","en":"Papacy","module":"middle-ages","def":"天主教会最高领袖及其制度，中世纪一度凌驾世俗君主之上。","analogy":"西欧的\"精神皇帝\"。"},
  {"id":"crusade","name":"十字军","en":"Crusade","module":"middle-ages","def":"11–13 世纪西欧以夺回圣地为名发动的多次宗教性军事远征。","analogy":"打着信仰旗号的\"东征\"。"},
  {"id":"black-death","name":"黑死病","en":"Black Death","module":"middle-ages","def":"14 世纪的鼠疫大流行，夺走欧洲约三分之一人口，加速封建瓦解。","analogy":"中世纪的\"大瘟疫\"。"},
  {"id":"nation-state","name":"民族国家","en":"Nation-state","module":"middle-ages","def":"以单一民族认同为基础的主权国家，近代世界的基本政治单位。","analogy":"\"一个民族一个国家\"。"},
  {"id":"manorialism","name":"庄园制","en":"Manorialism","module":"middle-ages","def":"中世纪以自给自足庄园为单位、农奴依附领主的经济制度。","analogy":"封建的\"经济底盘\"。"},
  {"id":"islam","name":"伊斯兰教","en":"Islam","module":"islam","def":"穆罕默德传播的一神教，主张顺从独一真主安拉，属亚伯拉罕诸教。","analogy":"\"顺从真主\"之教。"},
  {"id":"quran","name":"古兰经","en":"Quran","module":"islam","def":"伊斯兰教根本经典，穆斯林相信是真主通过穆罕默德降示的言语。","analogy":"伊斯兰的\"圣典\"。"},
  {"id":"caliph","name":"哈里发","en":"Caliph","module":"islam","def":"穆罕默德之后伊斯兰社群的领导者称号，意为\"继承者\"。","analogy":"先知的\"继任领袖\"。"},
  {"id":"sunni-shia","name":"逊尼与什叶","en":"Sunni & Shia","module":"islam","def":"伊斯兰两大派别，因哈里发继承权之争而分裂，核心信仰大体一致。","analogy":"同源的\"两大分支\"。"},
  {"id":"ottoman-empire","name":"奥斯曼帝国","en":"Ottoman Empire","module":"islam","def":"1453 年灭拜占庭、横跨欧亚非的伊斯兰大帝国，称雄数百年。","analogy":"伊斯兰世界的\"超级帝国\"。"},
  {"id":"mughal","name":"莫卧儿","en":"Mughal","module":"islam","def":"突厥蒙古后裔在印度建立的伊斯兰帝国，以宽容与泰姬陵闻名。","analogy":"印度的\"火药帝国\"。"},
  {"id":"maya","name":"玛雅","en":"Maya","module":"americas-africa","def":"中美洲文明，以文字、\"零\"和精密历法、阶梯金字塔著称。","analogy":"美洲的\"天文学家城邦\"。"},
  {"id":"aztec","name":"阿兹特克","en":"Aztec","module":"americas-africa","def":"墨西哥谷地的帝国，都城特诺奇蒂特兰，靠贡赋与征服称霸。","analogy":"湖中\"贡赋帝国\"。"},
  {"id":"inca","name":"印加","en":"Inca","module":"americas-africa","def":"安第斯山脉的庞大帝国，以道路、梯田和结绳记事管理国家。","analogy":"高山上的\"道路帝国\"。"},
  {"id":"trans-saharan-trade","name":"跨撒哈拉贸易","en":"Trans-Saharan trade","module":"americas-africa","def":"用骆驼商队跨越撒哈拉运送黄金与盐的贸易，造就西非帝国。","analogy":"沙漠里的\"金盐之路\"。"},
  {"id":"swahili","name":"斯瓦希里","en":"Swahili","module":"americas-africa","def":"东非沿海受印度洋贸易与阿拉伯文化影响形成的城邦与文化。","analogy":"非洲与印度洋的\"交汇文化\"。"},
  {"id":"renaissance","name":"文艺复兴","en":"Renaissance","module":"renaissance","def":"14 世纪始于意大利、重新发掘古典并以人为本的艺术与思想运动。","analogy":"古典文化的\"再生\"。"},
  {"id":"humanism","name":"人文主义","en":"Humanism","module":"renaissance","def":"文艺复兴的核心精神，重视人的尊严、理性与现世生活。","analogy":"\"以人为本\"。"},
  {"id":"reformation","name":"宗教改革","en":"Reformation","module":"renaissance","def":"马丁·路德发起、分裂西方基督教、催生新教的宗教运动。","analogy":"基督教的\"大分家\"。"},
  {"id":"columbian-exchange","name":"哥伦布大交换","en":"Columbian Exchange","module":"renaissance","def":"新旧大陆之间作物、动物、疾病的大规模互换，重塑全球人口与饮食。","analogy":"东西半球的\"物种大互换\"。"},
  {"id":"printing-press","name":"活字印刷","en":"Printing press","module":"renaissance","def":"古登堡改良的金属活字印刷机，使书籍量产、知识普及。","analogy":"近代的\"信息加速器\"。"},
  {"id":"scientific-revolution","name":"科学革命","en":"Scientific Revolution","module":"revolutions","def":"16–17 世纪用观察、实验与数学取代古代权威、奠定现代科学方法的变革。","analogy":"认识世界方式的\"换引擎\"。"},
  {"id":"enlightenment","name":"启蒙运动","en":"Enlightenment","module":"revolutions","def":"18 世纪以理性改造社会、主张自由平等人权与社会契约的思想运动。","analogy":"\"理性照亮社会\"。"},
  {"id":"social-contract","name":"社会契约","en":"Social contract","module":"revolutions","def":"政府权力源于人民同意、为保护权利而立的理论。","analogy":"人民与政府的\"约定\"。"},
  {"id":"nationalism","name":"民族主义","en":"Nationalism","module":"revolutions","def":"以民族认同为核心、主张建立独立统一民族国家的思潮。","analogy":"\"我的民族我的国\"。"},
  {"id":"liberalism","name":"自由主义","en":"Liberalism","module":"revolutions","def":"强调个人自由、法治、有限政府与市场的政治思想。","analogy":"\"自由与有限政府\"。"},
  {"id":"industrial-revolution","name":"工业革命","en":"Industrial Revolution","module":"industrial","def":"18 世纪后期始于英国、用机器与蒸汽动力取代手工的生产大变革。","analogy":"人类的第二次\"大升级\"。"},
  {"id":"capitalism","name":"资本主义","en":"Capitalism","module":"industrial","def":"以私有制、市场和资本逐利为核心的经济制度。","analogy":"\"资本驱动的经济\"。"},
  {"id":"marxism","name":"马克思主义","en":"Marxism","module":"industrial","def":"马克思创立、以阶级斗争和公有制为核心、批判资本主义的学说。","analogy":"对资本主义的\"批判理论\"。"},
  {"id":"imperialism","name":"帝国主义","en":"Imperialism","module":"industrial","def":"工业列强为原料、市场与势力范围而扩张殖民、统治他国的政策。","analogy":"工业强国的\"对外扩张\"。"},
  {"id":"socialism","name":"社会主义","en":"Socialism","module":"industrial","def":"主张以公有或公共调控实现更平等分配的广义思潮与制度。","analogy":"\"更平等\"的诉求。"},
  {"id":"total-war","name":"总体战","en":"Total war","module":"world-wars","def":"把国家全部人口、工业与资源投入的全面战争，平民与前线界限模糊。","analogy":"\"举国上阵\"的战争。"},
  {"id":"great-depression","name":"大萧条","en":"Great Depression","module":"world-wars","def":"1929 年股灾引发、持续整个 1930 年代的全球性经济危机。","analogy":"20 世纪的\"经济大寒冬\"。"},
  {"id":"fascism","name":"法西斯主义","en":"Fascism","module":"world-wars","def":"崇尚极端民族主义、领袖独裁与对外扩张、敌视民主的极权意识形态。","analogy":"极端民族主义的\"独裁政治\"。"},
  {"id":"holocaust","name":"大屠杀","en":"Holocaust","module":"world-wars","def":"纳粹有组织地屠杀约六百万犹太人及数百万其他受害者的种族灭绝。","analogy":"20 世纪最深重的\"反人类罪\"。"},
  {"id":"united-nations","name":"联合国","en":"United Nations","module":"world-wars","def":"1945 年成立、以维护和平与国际合作为宗旨的国际组织，设安理会。","analogy":"战后世界的\"协调平台\"。"},
  {"id":"cold-war","name":"冷战","en":"Cold War","module":"contemporary","def":"二战后美苏两大阵营间未直接全面开战的长期对抗（约 1947–1991）。","analogy":"\"不开火的全球对峙\"。"},
  {"id":"decolonization","name":"去殖民化","en":"Decolonization","module":"contemporary","def":"二战后亚非拉殖民地纷纷独立、殖民帝国瓦解的浪潮。","analogy":"殖民帝国的\"集体退场\"。"},
  {"id":"globalization","name":"全球化","en":"Globalization","module":"contemporary","def":"商品、资本、信息、人员跨国自由流动、世界日益一体化的进程。","analogy":"\"地球村\"的形成。"},
  {"id":"information-age","name":"信息时代","en":"Information Age","module":"contemporary","def":"以计算机、互联网与人工智能为标志、信息成为关键资源的时代。","analogy":"人类的第三次\"大升级\"。"},
  {"id":"european-union","name":"欧盟","en":"European Union","module":"contemporary","def":"欧洲国家让渡部分主权、追求一体化与持久和平的超国家联合体。","analogy":"区域一体化的\"样板\"。"}
];
})(window.WHS);
