/* 九大模块元信息 + 学习路线(路线图优先:首页"继续学习"按此推进)。
   short 用于侧边便利贴标签(≤2 字),no 是目录序号。 */
(function () {
  'use strict';

  [
    { id: 'guide',   no: 0, short: '导览', title: '学习导览',  sub: '怎么学 · 工具 · 路线图',      desc: '怎么学、常见误区、词典与工具怎么用、跟读/影子练习法。' },
    { id: 'pron',    no: 1, short: '发音', title: '发音',      sub: '字母 · 拼读 · 音标 · 连读',   desc: '美语的地基:26 字母、自然拼读、48 音标、重音、连读/弱读/失爆/浊化、缩读、语调节奏。' },
    { id: 'vocab',   no: 2, short: '词汇', title: '词汇',      sub: '词根词缀 · 场景词包',         desc: '不死背:词根词缀、构词法、高频词、搭配、一词多义、场景词包、功能基础词。' },
    { id: 'grammar', no: 3, short: '语法', title: '语法',      sub: '句型 · 时态 · 从句',          desc: '8 大词类、五大基本句型、12 时态、被动、三大从句、非谓语、虚拟语气、冠词介词难点。' },
    { id: 'listen',  no: 4, short: '听力', title: '听力',      sub: '精听 · 泛听 · 方法',          desc: '为什么听不懂、精听 vs 泛听、资源与方法。' },
    { id: 'speak',   no: 5, short: '口语', title: '口语表达',  sub: '高频句型 · 场景对话',         desc: '高频口语句型、地道美式表达、俚语习语、礼貌与语气、点餐/问路/社交/工作场景对话。' },
    { id: 'read',    no: 6, short: '阅读', title: '阅读',      sub: '长难句 · 阅读策略',           desc: '长难句拆解、略读/精读、阅读策略。' },
    { id: 'write',   no: 7, short: '写作', title: '写作',      sub: '句段篇 · 避坑 · 邮件',        desc: '句→段→篇、标点、拼写规则、中式英语避坑、邮件/简历。' },
    { id: 'culture', no: 8, short: '文化', title: '文化与语用', sub: '美英差异 · small talk',      desc: '美式 vs 英式差异、small talk 潜规则、文化梗、节日、网络缩略语。' },
    { id: 'travel',  no: 9, short: '旅行', title: '旅行英语',   sub: '全场景闭环 · 出发到回家',    desc: '一次完整出国旅程的实战英语:行前打底→机场航班→入境海关→交通→酒店→餐饮→购物→观光→就医应急→银行通讯→社交,每个场景配关键句点读、保命句与中国游客避坑。' }
  ].forEach(EMS.registerModule);

  /* 学习路线:有序课程 id。未编写的课程先占位(title 照写),
     引擎会显示为"待编写"并自动跳到下一个已注册的课。
     内容扩充时:写好课程文件 → 在 index.html 加 script 标签 → 此处占位自动激活。 */
  EMS.registerPath([
    { id: 'guide-01-howto',       module: 'guide', title: '欢迎:这个网站怎么用' },
    { id: 'guide-02-roadmap',     module: 'guide', title: '零基础路线图:先学什么后学什么' },
    { id: 'guide-03-myths',       module: 'guide', title: '学英语的五个常见误区' },
    { id: 'guide-04-tools',       module: 'guide', title: '词典与 AI 工具怎么用' },
    { id: 'guide-05-plan',        module: 'guide', title: '每天 30 分钟学习计划模板' },
    { id: 'guide-06-persist',     module: 'guide', title: '怎样坚持下去:习惯与动力' },

    { id: 'pron-01-alphabet',     module: 'pron', title: '26 个字母:字母名 ≠ 字母音' },
    { id: 'pron-02-phonics-intro', module: 'pron', title: '自然拼读:看见单词就会读的秘密' },
    { id: 'pron-03-short-vowels', module: 'pron', title: '五个短元音:a e i o u 的本音' },
    { id: 'pron-04-long-vowels',  module: 'pron', title: '长元音与神奇 e' },
    { id: 'pron-05-consonants-1', module: 'pron', title: '辅音(上):一看就会的 16 个' },
    { id: 'pron-06-consonants-2', module: 'pron', title: '辅音(下):中国人最容易错的 8 个' },
    { id: 'pron-07-th',           module: 'pron', title: '咬舌音 /θ/ /ð/:think ≠ sink' },
    { id: 'pron-08-stress',       module: 'pron', title: '重音:美语的灵魂节拍' },
    { id: 'pron-09-schwa',        module: 'pron', title: '弱读与 /ə/:美国人偷懒的艺术' },
    { id: 'pron-10-flap-t',       module: 'pron', title: '浊化 flap T:water 为什么像 wader' },
    { id: 'pron-11-stop-t',       module: 'pron', title: '失爆:that day 的 t 去哪了' },
    { id: 'pron-12-linking',      module: 'pron', title: '连读:not at all 为什么像 no-da-dall' },
    { id: 'pron-13-vowel-teams',  module: 'pron', title: '元音组合:ee oo ai oa,两个字母一个音' },
    { id: 'pron-14-r-vowels',     module: 'pron', title: 'r 控元音:ar or er,美式卷舌的家' },
    { id: 'pron-15-diphthongs',   module: 'pron', title: '双元音:oi oy ou ow,嘴巴会滑动' },
    { id: 'pron-16-contractions', module: 'pron', title: '缩读:gonna wanna gotta 的真面目' },
    { id: 'pron-17-intonation',   module: 'pron', title: '语调:同一句话,升调降调两个意思' },
    { id: 'pron-18-ipa-overview', module: 'pron', title: '48 音标总表 + 怎么用字典听发音' },

    { id: 'vocab-01-method',      module: 'vocab', title: '怎么背单词才不忘:音形义三位一体' },
    { id: 'vocab-02-roots',       module: 'vocab', title: '词根词缀:把长单词拆成乐高' },
    { id: 'vocab-03-prefixes',    module: 'vocab', title: '高频前缀:un re pre dis mis' },
    { id: 'vocab-04-suffixes',    module: 'vocab', title: '高频后缀:-er -tion -ful -less -ly' },
    { id: 'vocab-05-wordbuild',   module: 'vocab', title: '构词法:合成 · 转化 · 缩略' },
    { id: 'vocab-06-highfreq',    module: 'vocab', title: '高频词撑起半边天 + 怎么选词表' },
    { id: 'vocab-07-collocation', module: 'vocab', title: '搭配:make do take have 怎么配' },
    { id: 'vocab-08-polysemy',    module: 'vocab', title: '一词多义:get 和 run 的十张面孔' },
    { id: 'vocab-09-numbers',     module: 'vocab', title: '功能词包·数字、价格、电话号码读法' },
    { id: 'vocab-10-time',        module: 'vocab', title: '功能词包·时间、日期、星期、月份' },
    { id: 'vocab-11-restaurant',  module: 'vocab', title: '场景词包·餐厅点餐' },
    { id: 'vocab-12-shopping',    module: 'vocab', title: '场景词包·购物与问路' },

    { id: 'grammar-01-pos',       module: 'grammar', title: '八大词类:英语单词的"工种"' },
    { id: 'grammar-02-patterns',  module: 'grammar', title: '五大基本句型:英语句子的骨架' },
    { id: 'grammar-03-present',   module: 'grammar', title: '一般现在时 & 现在进行时' },
    { id: 'grammar-04-past',      module: 'grammar', title: '一般过去时 & 过去进行时' },
    { id: 'grammar-05-future',    module: 'grammar', title: '将来时:will 和 be going to' },
    { id: 'grammar-06-perfect',   module: 'grammar', title: '现在完成时:have done 到底在说什么' },
    { id: 'grammar-07-tenses',    module: 'grammar', title: '12 时态总览:一张表看懂全部' },
    { id: 'grammar-08-passive',   module: 'grammar', title: '被动语态:be + done' },
    { id: 'grammar-09-articles',  module: 'grammar', title: '冠词:a / an / the / 不加,老错点' },
    { id: 'grammar-10-prep',      module: 'grammar', title: '介词难点:in on at 的时间和地点' },
    { id: 'grammar-11-relative',  module: 'grammar', title: '定语从句:who which that' },
    { id: 'grammar-12-clauses',   module: 'grammar', title: '宾语从句 & 状语从句' },
    { id: 'grammar-13-nonfinite', module: 'grammar', title: '非谓语:to do / doing / done' },
    { id: 'grammar-14-subjunctive', module: 'grammar', title: '虚拟语气:If I were you…' },

    { id: 'listen-01-why',        module: 'listen', title: '为什么学过的词也听不懂' },
    { id: 'listen-02-intensive',  module: 'listen', title: '精听:一句一句抠到底' },
    { id: 'listen-03-extensive',  module: 'listen', title: '泛听:磨耳朵的正确姿势' },
    { id: 'listen-04-shadowing',  module: 'listen', title: '影子跟读法:听说一起练' },
    { id: 'listen-05-numbers',    module: 'listen', title: '数字、地名、人名:听力失分重灾区' },
    { id: 'listen-06-resources',  module: 'listen', title: '听力资源怎么选:分级不踩坑' },
    { id: 'listen-07-tvshows',    module: 'listen', title: '看美剧学英语的正确打开方式' },
    { id: 'listen-08-routine',    module: 'listen', title: '把听力练成日常习惯' },

    { id: 'speak-01-mindset',     module: 'speak', title: '开口关:从不敢说到敢说' },
    { id: 'speak-02-patterns',    module: 'speak', title: '万能高频口语句型,先背这些' },
    { id: 'speak-03-smalltalk',   module: 'speak', title: 'Small talk:美国人的寒暄开场' },
    { id: 'speak-04-natural',     module: 'speak', title: '地道美式表达 vs 中式直译' },
    { id: 'speak-05-agree',       module: 'speak', title: '同意、反对、拿不准怎么自然说' },
    { id: 'speak-06-polite',      module: 'speak', title: '礼貌与语气:委婉的艺术' },
    { id: 'speak-07-idioms',      module: 'speak', title: '俚语与习语:听懂美国人的"黑话"' },
    { id: 'speak-08-fillers',     module: 'speak', title: '口头禅与填充词:like, you know, well' },
    { id: 'speak-09-social',      module: 'speak', title: '场景对话·社交破冰' },
    { id: 'speak-10-phone',       module: 'speak', title: '场景对话·打电话' },
    { id: 'speak-11-work',        module: 'speak', title: '场景对话·工作沟通' },
    { id: 'speak-12-rescue',     module: 'speak', title: '卡壳救场:不会的词怎么绕过去' },

    { id: 'read-01-modes',        module: 'read', title: '精读 vs 泛读:两种读法各管什么' },
    { id: 'read-02-skimming',     module: 'read', title: '略读 skimming:30 秒抓大意' },
    { id: 'read-03-scanning',     module: 'read', title: '寻读 scanning:精准定位信息' },
    { id: 'read-04-mainclause',   module: 'read', title: '长难句拆解①:先揪出主干' },
    { id: 'read-05-modifiers',    module: 'read', title: '长难句拆解②:剥掉从句和修饰' },
    { id: 'read-06-guessing',     module: 'read', title: '猜词:不查字典也能读下去' },
    { id: 'read-07-materials',    module: 'read', title: '读物怎么选:分级阅读不踩坑' },
    { id: 'read-08-habit',        module: 'read', title: '把阅读变成每天的习惯' },

    { id: 'write-01-sentence',    module: 'write', title: '从写对一个句子开始' },
    { id: 'write-02-punctuation', module: 'write', title: '标点符号:英文的规矩和中文不同' },
    { id: 'write-03-spelling',    module: 'write', title: '拼写规则与最常拼错的词' },
    { id: 'write-04-paragraph',   module: 'write', title: '把句子连成段落:主题句+展开' },
    { id: 'write-05-essay',       module: 'write', title: '把段落组成文章:开头-主体-结尾' },
    { id: 'write-06-connectors',  module: 'write', title: '连接词:让文章有逻辑流' },
    { id: 'write-07-chinglish',   module: 'write', title: '写作版中式英语避坑' },
    { id: 'write-08-email',       module: 'write', title: '写邮件:正式与非正式' },
    { id: 'write-09-resume',      module: 'write', title: '写简历与求职信' },
    { id: 'write-10-polish',      module: 'write', title: '改写润色:让句子更地道' },

    { id: 'culture-01-us-uk',     module: 'culture', title: '美式 vs 英式:到底差在哪' },
    { id: 'culture-02-tipping',   module: 'culture', title: '小费文化:谁该给、给多少' },
    { id: 'culture-03-privacy',   module: 'culture', title: '隐私与边界:这些别随便问' },
    { id: 'culture-04-holidays',  module: 'culture', title: '美国主要节日与习俗' },
    { id: 'culture-05-textspeak', module: 'culture', title: '网络与短信缩略语:lol btw asap' },
    { id: 'culture-06-humor',     module: 'culture', title: '美式幽默与玩笑的分寸' },
    { id: 'culture-07-manners',   module: 'culture', title: '餐桌与做客礼仪' },
    { id: 'culture-08-taboo',     module: 'culture', title: '禁忌话题与政治正确' },
    { id: 'culture-09-memes',     module: 'culture', title: '日常文化梗与流行引用' },

    { id: 'travel-01-survival',     module: 'travel', title: '旅行模块导览 + 万能保命 10 句' },
    { id: 'travel-02-patterns',     module: 'travel', title: '8 大黄金句型:覆盖 80% 旅行需求' },
    { id: 'travel-03-numbers',      module: 'travel', title: '数字·价格·金钱:别听错说错' },
    { id: 'travel-04-time',         module: 'travel', title: '时间·日期·航班时刻' },
    { id: 'travel-05-polite',       module: 'travel', title: '礼貌核心句 + 旅行版 Chinglish 避坑' },
    { id: 'travel-06-checkin',      module: 'travel', title: '机场①:值机柜台 check-in' },
    { id: 'travel-07-security',     module: 'travel', title: '机场②:安检 TSA' },
    { id: 'travel-08-boarding',     module: 'travel', title: '机场③:登机口·候机·转机' },
    { id: 'travel-09-onplane',      module: 'travel', title: '机场④:在飞机上' },
    { id: 'travel-10-baggage',      module: 'travel', title: '机场⑤:行李丢失/延误报失' },
    { id: 'travel-11-immigration',  module: 'travel', title: '入境①:边检窗口问答' },
    { id: 'travel-12-customs',      module: 'travel', title: '入境②:海关申报 + 提取行李' },
    { id: 'travel-13-rideshare',    module: 'travel', title: '交通①:出租车·Uber·Lyft' },
    { id: 'travel-14-transit',      module: 'travel', title: '交通②:地铁·公交·长途火车' },
    { id: 'travel-15-carrental',    module: 'travel', title: '交通③:租车 car rental' },
    { id: 'travel-16-directions',   module: 'travel', title: '交通④:问路 + GPS 失灵救命句' },
    { id: 'travel-17-hotel-checkin', module: 'travel', title: '酒店①:入住 check-in' },
    { id: 'travel-18-hotel-issues', module: 'travel', title: '酒店②:房间问题 + 客房服务' },
    { id: 'travel-19-hotel-checkout', module: 'travel', title: '酒店③:退房 + 投诉升级' },
    { id: 'travel-20-dining-order', module: 'travel', title: '餐饮①:预订 + 入座点餐' },
    { id: 'travel-21-dining-dietary', module: 'travel', title: '餐饮②:过敏与特殊饮食必说句' },
    { id: 'travel-22-dining-pay',   module: 'travel', title: '餐饮③:结账小费 + 快餐咖啡' },
    { id: 'travel-23-shopping',     module: 'travel', title: '购物:询问·试穿·退换·退税' },
    { id: 'travel-24-sightseeing',  module: 'travel', title: '观光:门票·导览·拍照·景点应急' },
    { id: 'travel-25-medical',      module: 'travel', title: '应急①:就医症状描述 + 药店' },
    { id: 'travel-26-emergency',    module: 'travel', title: '应急②:拨 911 + 防骗拒推销' },
    { id: 'travel-27-money-comms',  module: 'travel', title: '银行通讯:ATM·换汇·信用卡·SIM 卡' },
    { id: 'travel-28-smalltalk',    module: 'travel', title: '社交:Small talk 闲聊模板' },
    { id: 'travel-29-appendix',     module: 'travel', title: '收尾闭环:美式vs英式·标志缩略·行前清单' }
  ]);
})();
