/* generated by tools/build.js */
window.SLP=window.SLP||{};
SLP.META=SLP.META||{};SLP.META.nmods=8;
SLP.modules=[
 {
  "id": "sleep-basics",
  "name": "睡眠基础",
  "icon": "🌙",
  "soft": "var(--teal-soft)",
  "desc": "先搞懂睡眠本身：周期怎么走、生物钟怎么对时、困意从哪来，后面的方法才有根。",
  "lessons": [
   {
    "id": "sleep-basics-01",
    "title": "人为什么要睡觉：大脑的夜间大扫除"
   },
   {
    "id": "sleep-basics-02",
    "title": "睡眠周期：一夜要走过四到六轮"
   },
   {
    "id": "sleep-basics-03",
    "title": "生物钟：藏在脑子里的一台 24 小时钟"
   },
   {
    "id": "sleep-basics-04",
    "title": "睡多久才够：别拿 8 小时当铁律"
   },
   {
    "id": "sleep-basics-05",
    "title": "睡眠债：欠下的觉能不能补回来"
   },
   {
    "id": "sleep-basics-06",
    "title": "腺苷与咖啡因：困意是怎么被堵住的"
   },
   {
    "id": "sleep-basics-07",
    "title": "褪黑素：它是报时员，不是安眠药"
   },
   {
    "id": "sleep-basics-08",
    "title": "睡眠与记忆：白天学的，晚上才存住"
   },
   {
    "id": "sleep-basics-09",
    "title": "梦与 REM：大脑的夜间剧场"
   }
  ]
 },
 {
  "id": "sleep-problems",
  "name": "睡眠问题",
  "icon": "😴",
  "soft": "var(--alert-soft)",
  "desc": "失眠、打鼾、早醒、腿不舒服、倒班——常见睡眠困扰的成因与分界线。",
  "lessons": [
   {
    "id": "sleep-problems-01",
    "title": "失眠：躺下就是睡不着，问题出在哪"
   },
   {
    "id": "sleep-problems-02",
    "title": "入睡困难的三种典型：你是哪一种"
   },
   {
    "id": "sleep-problems-03",
    "title": "打鼾与睡眠呼吸暂停：被掐住的呼吸"
   },
   {
    "id": "sleep-problems-04",
    "title": "不宁腿与周期性肢体运动：腿上有蚂蚁在爬"
   },
   {
    "id": "sleep-problems-05",
    "title": "早醒：凌晨四点醒来意味着什么"
   },
   {
    "id": "sleep-problems-06",
    "title": "昼夜节律紊乱：倒班、时差与夜猫子"
   },
   {
    "id": "sleep-problems-07",
    "title": "梦游、噩梦与夜惊：睡着的另一半故事"
   },
   {
    "id": "sleep-problems-08",
    "title": "睡眠与年龄：老了觉少是真的吗"
   },
   {
    "id": "sleep-problems-09",
    "title": "什么时候该看睡眠门诊"
   }
  ]
 },
 {
  "id": "sleep-improve",
  "name": "改善睡眠",
  "icon": "🛏",
  "soft": "var(--blue-soft)",
  "desc": "睡眠卫生打地基，刺激控制、睡眠限制、放松训练、光照校准——有证据的做法一条条讲清。",
  "lessons": [
   {
    "id": "sleep-improve-01",
    "title": "睡眠卫生：十条基本功"
   },
   {
    "id": "sleep-improve-02",
    "title": "刺激控制：让床只代表一件事"
   },
   {
    "id": "sleep-improve-03",
    "title": "睡眠限制：少躺一点，反而睡得香"
   },
   {
    "id": "sleep-improve-04",
    "title": "睡眠效率：一个数字读懂你的睡眠"
   },
   {
    "id": "sleep-improve-05",
    "title": "CBT-I：失眠的一线\"药\"其实是行为"
   },
   {
    "id": "sleep-improve-06",
    "title": "放松训练：把身体的\"油门\"松下来"
   },
   {
    "id": "sleep-improve-07",
    "title": "光照与黑暗：用光给生物钟对时"
   },
   {
    "id": "sleep-improve-08",
    "title": "卧室环境：温度、光线与噪音"
   },
   {
    "id": "sleep-improve-09",
    "title": "午睡：睡多久、什么时候睡才对"
   },
   {
    "id": "sleep-improve-10",
    "title": "睡前仪式：给大脑一段下坡路"
   }
  ]
 },
 {
  "id": "stress-basics",
  "name": "压力是什么",
  "icon": "⚡",
  "soft": "var(--warn-soft)",
  "desc": "压力不是\"想太多\"，是一整套有生理通路的身体反应。先看懂它，才好跟它打交道。",
  "lessons": [
   {
    "id": "stress-basics-01",
    "title": "压力：身体的\"备战状态\""
   },
   {
    "id": "stress-basics-02",
    "title": "战斗—逃跑—冻结：一套古老的程序"
   },
   {
    "id": "stress-basics-03",
    "title": "HPA 轴与皮质醇：压力的激素通路"
   },
   {
    "id": "stress-basics-04",
    "title": "急性压力 vs 慢性压力：区别到底在哪"
   },
   {
    "id": "stress-basics-05",
    "title": "好压力与坏压力：倒 U 形曲线"
   },
   {
    "id": "stress-basics-06",
    "title": "压力如何伤身：从心血管到免疫"
   },
   {
    "id": "stress-basics-07",
    "title": "压力与大脑：记忆、注意与决策"
   },
   {
    "id": "stress-basics-08",
    "title": "压力的人体信号：身体比嘴巴诚实"
   },
   {
    "id": "stress-basics-09",
    "title": "压力不是敌人：把威胁读成挑战"
   }
  ]
 },
 {
  "id": "stress-coping",
  "name": "应对压力",
  "icon": "🧘",
  "soft": "var(--ok-soft)",
  "desc": "能改的去改，改不了的去调情绪——十种有证据的应对方法，配上具体做法。",
  "lessons": [
   {
    "id": "stress-coping-01",
    "title": "应对方式大盘点：问题聚焦还是情绪聚焦"
   },
   {
    "id": "stress-coping-02",
    "title": "认知重评：每天都能做的三句改写"
   },
   {
    "id": "stress-coping-03",
    "title": "呼吸：身体自带的那只降速阀"
   },
   {
    "id": "stress-coping-04",
    "title": "表达性书写：把脑子里的乱麻倒出来"
   },
   {
    "id": "stress-coping-05",
    "title": "正念：不评判地待在此刻"
   },
   {
    "id": "stress-coping-06",
    "title": "冥想与身体扫描：给注意力一个去处"
   },
   {
    "id": "stress-coping-07",
    "title": "时间管理与优先级：从\"全都急\"到\"先做一件\""
   },
   {
    "id": "stress-coping-08",
    "title": "边界与拒绝：把\"不\"说出口"
   },
   {
    "id": "stress-coping-09",
    "title": "社会支持：别一个人扛"
   },
   {
    "id": "stress-coping-10",
    "title": "运动：最被低估的抗压药"
   }
  ]
 },
 {
  "id": "emotion",
  "name": "情绪与心理",
  "icon": "💙",
  "soft": "var(--purple-soft)",
  "desc": "焦虑、抑郁、倦怠、反刍——认识它们的样子、边界与可用的办法，也包括什么时候必须求助。",
  "lessons": [
   {
    "id": "emotion-01",
    "title": "焦虑：警报器太灵敏"
   },
   {
    "id": "emotion-02",
    "title": "惊恐发作：几分钟的猛烈风暴"
   },
   {
    "id": "emotion-03",
    "title": "抑郁：不是\"想开点\"就能好"
   },
   {
    "id": "emotion-04",
    "title": "职业倦怠：三重耗竭的累积"
   },
   {
    "id": "emotion-05",
    "title": "反刍思维：脑子停不下来的那个循环"
   },
   {
    "id": "emotion-06",
    "title": "情绪调节：识别、命名、再选择"
   },
   {
    "id": "emotion-07",
    "title": "自我关怀：对自己像对朋友一样"
   },
   {
    "id": "emotion-08",
    "title": "完美主义与拖延：同一个硬币的两面"
   },
   {
    "id": "emotion-09",
    "title": "心理韧性：它不是天生的"
   }
  ]
 },
 {
  "id": "body-mind",
  "name": "身心联结",
  "icon": "🔗",
  "soft": "var(--blue-soft)",
  "desc": "咖啡、酒、饮食、屏幕、运动、迷走神经——日常生活里那些直接影响睡眠与压力的变量。",
  "lessons": [
   {
    "id": "body-mind-01",
    "title": "咖啡因：下午那杯，晚上还在一半"
   },
   {
    "id": "body-mind-02",
    "title": "酒精：见效最快，也最伤睡眠"
   },
   {
    "id": "body-mind-03",
    "title": "饮食与睡眠：吃什么、什么时候吃"
   },
   {
    "id": "body-mind-04",
    "title": "屏幕与蓝光：睡前刷手机的代价"
   },
   {
    "id": "body-mind-05",
    "title": "运动：什么时候练最不影响睡眠"
   },
   {
    "id": "body-mind-06",
    "title": "迷走神经与 HRV：身体的恢复仪表盘"
   },
   {
    "id": "body-mind-07",
    "title": "光照、季节与情绪"
   },
   {
    "id": "body-mind-08",
    "title": "睡眠惯性：为什么早上那么难起来"
   }
  ]
 },
 {
  "id": "help",
  "name": "求助与工具",
  "icon": "🧭",
  "soft": "var(--teal-soft)",
  "desc": "量表怎么用、什么时候必须就医、心理咨询与药物、以及一份能立刻开始的 30 天计划。",
  "lessons": [
   {
    "id": "help-01",
    "title": "自评量表怎么用：先看清，再行动"
   },
   {
    "id": "help-02",
    "title": "什么时候必须就医：红旗信号清单"
   },
   {
    "id": "help-03",
    "title": "睡眠门诊：去了会做什么检查"
   },
   {
    "id": "help-04",
    "title": "心理咨询：流派与怎么选"
   },
   {
    "id": "help-05",
    "title": "安眠药：什么时候用，怎么停"
   },
   {
    "id": "help-06",
    "title": "就医准备：带上你的睡眠日记"
   },
   {
    "id": "help-07",
    "title": "求助不是软弱，而是能力"
   },
   {
    "id": "help-08",
    "title": "给自己的一份 30 天计划"
   }
  ]
 }
];
SLP.flatLessons=["sleep-basics-01","sleep-basics-02","sleep-basics-03","sleep-basics-04","sleep-basics-05","sleep-basics-06","sleep-basics-07","sleep-basics-08","sleep-basics-09","sleep-problems-01","sleep-problems-02","sleep-problems-03","sleep-problems-04","sleep-problems-05","sleep-problems-06","sleep-problems-07","sleep-problems-08","sleep-problems-09","sleep-improve-01","sleep-improve-02","sleep-improve-03","sleep-improve-04","sleep-improve-05","sleep-improve-06","sleep-improve-07","sleep-improve-08","sleep-improve-09","sleep-improve-10","stress-basics-01","stress-basics-02","stress-basics-03","stress-basics-04","stress-basics-05","stress-basics-06","stress-basics-07","stress-basics-08","stress-basics-09","stress-coping-01","stress-coping-02","stress-coping-03","stress-coping-04","stress-coping-05","stress-coping-06","stress-coping-07","stress-coping-08","stress-coping-09","stress-coping-10","emotion-01","emotion-02","emotion-03","emotion-04","emotion-05","emotion-06","emotion-07","emotion-08","emotion-09","body-mind-01","body-mind-02","body-mind-03","body-mind-04","body-mind-05","body-mind-06","body-mind-07","body-mind-08","help-01","help-02","help-03","help-04","help-05","help-06","help-07","help-08"];
